### ISSUE TITLE
Review peer

### ISSUE THREAD

**Issue by amorteguiandres** [edilbertoespinosa/mercado-liebre#1]
Header:
● Logo OK
● Barra de búsqueda OK
● Comprá en cuotas y sin tarjeta de crédito OK
● Barra de navegación: Ajustar la navbar de manera horizontal 
● Ofertas OK
● Tiendas Oficiales OK
● Vender OK
● Ayuda OK
● Login OK
● Registro OK
● Mis compras OK
Main:
● Sección basada en las últimas visitas OK
● Sección de ofertas OK
Footer:
● Pagá con tarjeta o en efectivo OK
● Envío gratis desde $ 2.500 OK
● Seguridad, de principio a fin OK
● Copyright © 1999-2022 MercadoLiebre S.R.L. Corregir el año !

    Haciendo foco en los estilos del pie de página (Footer):
    ● ¿El contenido de todos los artículos está centrado? Si
    ● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
    10 píxeles? Si
    ¿El sitio se adapta a distintas resoluciones de pantalla? SI
    ¿El sitio cuenta con un formulario de registro de usuarios? Si
    ¿El sitio cuenta con un formulario de login? Si
    ¿Se muestran mensajes de error cuando un usuario coloca información
    equivocada en un campo de los formularios? Si
    ¿El search bar es un formulario? Si
    ¿Se utilizan animaciones y propiedades de transición de CSS? Si
    Para terminar el feedback, menciona algunas cosas que crees que tu
    compañero hizo bien.
    Me gusto el codigo bien organizado y legible
    10.Por último, menciona algo que tu compañero podría mejorar.
    Terminar algunas cosas de estilos de resto muy bien

**Comment by edilbertoespinosa** [comment]
Andres. Muchas Gracias por tu tiempo para el code review y por tus comentarios que nutren mi  codigo.
