### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by florguede** [edilbertoespinosa/mercado-liebre#2]
- [x] 1 - Cumple - La estructura del sitio cuenta con todos los elementos solicitados para cada sección.
- [x] 2 - No cumple - Falta aplicar el margin de 10px.
- [x] 3 - Cumple - El sitio se adapta a todas las resoluciones de pantalla.
- [x] 4 - Cumple - El sitio cuenta con un formulario de registro de usuarios
- [x] 5 - Cumple - El sitio cuenta con un formulario de login
- [x] 6 - Cumple - Se muestran mensajes de error cuando un usuario coloca información equivocada
- [x] 7 - Cumple - El search bar es un formulario.
- [x] 8 - Cumple - Se usan animaciones y propiedades de transición.
- [x] 9 - Hizo bien: estructura del sitio, formularios, animaciones, diseño. Todo excelente! 
- [x] 10 - Puede mejorar: barra de navegación con display flex y en los formularios de registro y login agregar header y footer.

**Comment by edilbertoespinosa** [comment]
Flor te agradezco tu tiempo para el peer review y tus comentarios que nutrieron mi proyecto.
